### ISSUE TITLE
User can view a list of video games, with 20 games on each page

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/ajax-project#1]
## 💰 Motivation

Gamers will want to see which video games are currently popular. 

## 📐 Plan

Create a responsive gallery that allows users to see thumbnails and titles of popular video games.

## 🖼️ Wireframes

<img width="470" alt="feature-1-mobile" src="https://user-images.githubusercontent.com/46775983/192338039-ca3a14fd-9309-4fb2-b8a0-96c14b21b29f.png">
<img width="662" alt="feature-1-desktop" src="https://user-images.githubusercontent.com/46775983/192338052-59190280-5290-46c0-9c20-267c57904be2.png">

## ✅ Task List

- [x] Add a header bar to the HTML file.
  - [x] Ensure its position is fixed.
- [x] Add a div[data-view="featured"] to the HTML file.
  - [x] Add name of current view and page number.
- [x] Add a data model to the JavaScript (data) file.
  - [x] Add a view property with a value of 'featured'.
  - [x] Create a localStorage item named 'game-data'.
  - [x] Ensure the item appears on Application tool.
- [x] Add a div[class="card-view"] to the HTML file..
  - [x] Add dummy cards and style them to match wireframe.
  - [x] Ensure dummy card layout matches wireframe for mobile and desktop.
- [x] Add back button, page number, and next button below dummy cards.
- [x] Ensure overall page layout matches wireframe for mobile and desktop.
- [x] Declare a variable that has a value of the URL for a list of games. 
- [x] Define a function named 'getData' with one parameter for a string (URL) that will be used for a GET request.
  - [x] Add a new XMLHttpRequest object.
  - [x] Get object of list of games.
- [x] Define a function named 'renderCards' with one parameter for an array (from object) that creates a DOM tree for a card.
  - [x] Use a loop to create a DOM tree for each element in the array.
    - [x] Use the .background_image property for the thumbnail.
    - [x] Use the .name property for the title.
    - [x] Append the card to div[class="card-wrapper"].
- [x] Add an event listener for the XMLHttpRequest object that calls the 'renderCards' function with the .results property as an argument when the 'load' event is fired.
  - [x] Ensure that the cards render properly.
- [x] Remove dummy cards from the HTML file.
- [x] Add an event listener for the back button that renders the previous page's cards when the 'click' event is fired.
  - [x] Ensure that the back button is hidden on page 1.
  - [x] Ensure that the previous page's cards render properly.
  - [x] Ensure that the page number is updated properly.
- [x] Add an event listener for the next button that renders the next page's cards when the 'click' event is fired.
  - [x] Ensure that the next button is hidden if there is no .next property 
  - [x] Ensure that the next page's cards render properly.
  - [x] Ensure that the page number is updated properly.

**Clean Up**
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
