### ISSUE TITLE
User can view the details for a single game

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/ajax-project#2]
## 💰 Motivation

Gamers will want to read about a particular video game.

## 📐 Plan

Create a drill-down view that allows users to see a description and additional details of a particular video game.

## 🖼️ Wireframes

<img width="470" alt="feature-2-mobile" src="https://user-images.githubusercontent.com/46775983/192355894-7d4882d6-b57d-4c1b-9a4f-fb4be7a2425e.png">
<img width="662" alt="feature-2-desktop" src="https://user-images.githubusercontent.com/46775983/192355908-43cd4785-70af-41c2-90e0-db8fc24f3546.png">

## ✅ Task List

- [x] Add a div[data-view="detail"] to the HTML file.
  - [x] Add a 'back' link to featured view.
    - [x] Add an event listener for the 'back' link that changes the view to "featured" when the 'click' event is fired.      
      - [x] Update the view property in the data model to 'detail'.
      - [x] Ensure the detail view is hidden and the featured view is visible. 
      - [x] Ensure the view property in the data model is updated correctly.
  - [x] Add empty h2 element for game title.
  - [x] Add dummy game detail and style it to match wireframe.
  - [x] Ensure dummy game detail layout matches wireframe for mobile and desktop.
- [x] In 'renderCard' for the card variable, set a 'data-url' attribute with a value of the URL to its respective game.
- [x] Add an event listener for .card-view that checks for 'click' events when a 'click' event is fired on a card.
  - [x] Update the view property in the data model to 'detail'.
  - [x] Call 'getData' and pass in the card's 'data-url' value as an argument.
  - [x] Ensure that the 'click' event is only fired when clicking on a card.
- [x] In 'getData', add an if/if else statement that checks for the current view
  - [x] Call 'renderCard' if the current view is 'featured'.
  - [x] Call 'fillDetail' if the current view is 'detail'.
- [x] Define a function named 'fillDetail' with one parameter for an object (from 'getData') that populates div[class="detail-view"].
- [x] Ensure that div[class="detail-view"] shows the correct game detail
- [x] Remove dummy game detail from the HTML file.
- [x] Ensure div[data-view="detail"] is hidden by default.

**Clean Up**
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
