### ISSUE TITLE
User can search video games

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/ajax-project#3]
## 💰 Motivation

Gamers will want to search for a particular video game.

## 📐 Plan

Create a search bar that will dynamically show linked video game titles that match the user's input.

## 🖼️ Wireframes

<img width="470" alt="feature-3-mobile" src="https://user-images.githubusercontent.com/46775983/192357574-378717ca-22a1-4707-93b5-891e8f732ace.png">
<img width="662" alt="feature-3-desktop1" src="https://user-images.githubusercontent.com/46775983/192357587-a12b6ebe-02dd-4eb8-b974-3e6beed4ca69.png">
<img width="324" alt="feature-3-desktop2" src="https://user-images.githubusercontent.com/46775983/192357600-252699d2-e3ac-4483-91b6-29ea924a9f79.png">

## ✅ Task List

- [x] Add a search icon to the header.
- [x] Add a div[data-view="search"] below div[data-view="detail"].
  - [x] Add a modal, form, and back button.
  - [x] Ensure the form matches the wireframe for both mobile and desktop.
  - [x] Ensure the modal can be toggled via search icon or back button.
  - [x] Ensure the view variable is updated to 'search'.
- [x] Declare a variable named 'timerId' and set it to 'null'. 
- [x] Add an event listener to the form that checks for 'keyup' events.
  - [x] Declare a variable named 'searchUrl' with a value of the URL (with a search parameter). 
  - [x] Concatenate 'searchURL' and the current input. 
  - [x] Add an if/else statement.
    - [x] If there is a 'keydown' event AND a timeout currently in place:
      - [x] Call the 'clearTimeout' function.
        - [x] Ensure the ID of 'setTimeout' is passed an an argument. 
    - [x] Else, call the 'setTimeout' function.
      - [x] Ensure that 'getData' is passed with 'searchUrl' as an argument.
      - [x] Ensure that the delay is set to 0.5. seconds (500 milliseconds).
      - [x] Ensure that the return of the function call is assigned to 'timerId'.
      - [x] Ensure 'timerId' is set to 'null' after 'getData' is called.
- [x] In 'getData', expand the if else statement checking if the current view is 'search'.
  - [x] Call a function named 'renderResults' that passes in the object retrieved as an argument. 
  - [x] Comment out the function call for now.
- [x] Define a function named 'renderResults' that has one parameter for an array.
  - [x] Loop through the first 10 elements of the array.
    - [x] Generate a list item element with a nested anchor element.
      - [x] Set a 'data-url' attribute to with a value of the .slug property of the array.
      - [x] Set the textContent to the value of the .name property in the array.
    - [x] Append the list item elements to the results-containing element.  
  - [x] Ensure the results are updated with periodically when the input is updated.
- [x] Ensure the search icon (on the modal) appears as a clickable link.
- [x] Ensure the search results appear as clickable links.
- [x] Ensure that the search bar and results match the wireframe for both mobile and desktop.

**Clean Up**
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
