### ISSUE TITLE
User can view search results

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/ajax-project#4]
## 💰 Motivation

Gamers will want to see a list of video games that match what was entered in their search.

## 📐 Plan

Create a responsive gallery that allows users to see thumbnails and titles of video games as a result of their search input.

## 🖼️ Wireframes

<img width="634" alt="feature-4-mobile" src="https://user-images.githubusercontent.com/46775983/192359064-f63a07c4-90e1-4722-93f1-a0beef5aa693.png">
<img width="662" alt="feature-4-desktop1" src="https://user-images.githubusercontent.com/46775983/192359091-a197474b-ef25-45df-b702-610406bc44bb.png">
<img width="662" alt="feature-4-desktop2" src="https://user-images.githubusercontent.com/46775983/192359102-d0b83793-e8e0-45c9-a2f5-b3c49fd6236b.png">

## ✅ Task List

**Clicking a single search result link:**
- [x] Query the containing element of the search result links.
- [x] Add a 'click' event listener to the containing element.
  - [x] Ensure the event is only fired when a search result link is clicked.
  - [x] Get the 'data-url' attribute's value from the clicked link. 
  - [x] Update the 'view' variable to 'detail'. (!important)
  - [x] Call 'getData' and pass in the value of 'data-url'.
  - [x] Hide the 'search' view (and the 'featured' view) and show the 'detail' view.
- [x] Ensure the 'detail' view shows the appropriate game and related information.
- [x] Ensure the 'back' link goes to the 'featured' view.
- [x] Ensure the 'view' variable is updated to 'featured'.

**Clicking the search button on the search bar:**
- [x] Query the search button on the search bar.
- [x] Add a 'click' event listener to the search bar button.
  - [x] Ensure the event is only fired when the search bar button is clicked.
  - [x] Get the expression (full search URL) of the current input.
  - [x] Update the 'view' variable to 'featured'. (!important).
  - [x] Call 'getData' and pass in the full search URL.
  - [x] Hide the 'search' view (and the 'detail' view) and show the 'featured' view.
    - [x] Change 'Feature' to 'Search Results' in div[data-view="featured"].
- [x] Ensure the 'featured' ('search results') view shows the appropriate games.
- [x] Add a navigation link to the header that says 'Featured'.
  - [x] Ensure the link reverts the modified 'featured' view to its original view.
  - [x] Ensure the 'view' variable is updated to 'featured'.

**Clean Up**
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
