### ISSUE TITLE
User can bookmark a video game

### ISSUE THREAD

**Issue by jiannicariaga** [jiannicariaga/ajax-project#5]
## 💰 Motivation

Gamers will want to save a list video games to read about later.

## 📐 Plan

Create a collection view where users can see the video games they bookmarked.  

## 🖼️ Wireframes

<img width="635" alt="feature-5-mobile1" src="https://user-images.githubusercontent.com/46775983/192360823-7e95dc80-bca4-49ce-9c2b-3cf8b5979973.png">
<img width="140" alt="feature-5-mobile2" src="https://user-images.githubusercontent.com/46775983/192360836-eafe6e4b-a0da-4e35-b7c5-67d1d71f914a.png">
<img width="662" alt="feature-5-desktop1" src="https://user-images.githubusercontent.com/46775983/192360843-98e27ebc-63b2-463a-bb16-f4b28569bf2f.png">
<img width="662" alt="feature-5-desktop2" src="https://user-images.githubusercontent.com/46775983/192360852-e40f5f05-2698-45fe-9bd4-5e4061668c98.png">
<img width="323" alt="feature-5-desktop3" src="https://user-images.githubusercontent.com/46775983/192360863-f87b7bab-3d52-419b-bb5c-b15dbeed709e.png">

## ✅ Task List

**Bookmark Icons**
- [x] Add a bookmark icon to the header next to the search icon.
  - [x] Ensure the header matches the wireframe for both mobile and desktop.
- [x] Add a bookmark icon to the detail card across from "About".
  - [x] Ensure the detail card matches the wireframe for both mobile and desktop. 

**Bookmarks View**
- [x] Add an event listener to the header bookmark icon that listens for the 'click' event.
  - [x] Update the view variable to featured. 
  - [x] Update the view label to "Bookmarks".
  - [x] Unhide the back button that goes to the featured view. 
  - [x] Hide the page buttons pm the featured view.
  - [x] Clear the current cards on the featured view.

**Adding/Removing Bookmarks**
- [x] Add a property to the data model named 'bookmarks' with a value of an empty array.
- [x] Declare a variable named currentDetail and assign it an empty object.
  - [x] Add two properties to the object: 'cardInfo' and 'detailUrl'.
  - [x] The value of 'cardInfo' should be an object.
  - [x] Add two properties to the object: 'background_image' and 'name'
  - [x] Ensure the value for both properties are empty strings.
  - [x] The value of detailUrl should be an empty string.
- [x] In the event listener for the $cards variable, assign the return of the argument that is passed into getData to currentDetail.detailUrl.
- [x] In getData, assign the .name and .backround_image properties of the object and assign them to currentDetail.cardInfo.name and currentDetail.cardInfo.background_image, respectively.
- [x] In fillDetail, add a for loop that checks each element in the bookmark property of the data model.
  - [x] Add an if statement checking if the currentDetail.detailUrl is found in the bookmarks property of the data model.
  - [x] If there is a match, update the detail bookmark icon's style to filled.
  - [x] If there is no match, ensure the detail bookmark icon's style remains outlined.
- [x] Add an event listener to the detail bookmark icon that listens for 'click' events.
  - [x] Add a for loop that checks each element in the bookmark property of the data model.
    - [x] Add an if statement checking if the currentDetail.detailUrl is found in the bookmarks property of the data model.
      - [x] If there is a match, remove the respective element from the array.
      - [x] If there is no match, push currentDetail to the bookmarks property of the data model.
- [x] Ensure the data model is updated properly.
- [x] Ensure the bookmark icon toggles between an outlined style and a filled style when clicked.

**Rendering Bookmarks**
- [x] In the event listener for the header bookmark icon, call renderCards with the value of the bookmarks property as an argument.
- [x] Ensure the bookmarks render properly.

**Clean Up**
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
